apps/accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from .views import (
    LoginView,
    RegistrationView,
    PasswordResetView
)
app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html', success_url='/accounts/password_reset/done'), name='password_reset'),
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(success_url='/accounts/reset/done'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

elearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.landing.urls', namespace='landing')),
    path('accounts/', include('apps.accounts.urls', namespace='authentication')),
    path('courses/', include('apps.courses.urls', namespace='course'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.signals import pre_save


class CustomUserManager(BaseUserManager):

    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Email cannot be blank.')
        
        if not password:
            raise ValueError('Password cannot be blank.')
        
        user = self.model(
            email= self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, password):
        user  = self.create_user(email, password=password)
        user.staff = True
        user = user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password=password
        )
        user.staff = True
        user.admin = True
        user = user.save(using=self._db)
        return user
    

class User(AbstractBaseUser):
    email = models.EmailField(max_length=250, unique=True)
    admin = models.BooleanField(default=False)
    student = models.BooleanField(verbose_name='As a Student', default=False)
    instructor = models.BooleanField(verbose_name='As an Instructor', default=False)
    staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return f'{self.email}'

    def has_perm(self, obj=None):
        return True
    
    def has_module_perms(self, app_label):
        return True
    
    def get_fullname(self):
        return self.email

    def get_shortname(self):
        return self.email.split('@')[0]

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

def pre_save_listener(sender, instance, *args, **kwargs):
    if instance.student:
        instance.instructor = False
    if instance.instructor:
        instance.student = False

pre_save.connect(receiver=pre_save_listener, sender=User)

apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, ReadOnlyPasswordHashField, PasswordChangeForm
from .models import User

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'student', 'instructor')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.active = True

        if commit:
            user.save()
        return user


class UserAdminRegisterForm(forms.ModelForm):
    ''' class for allowing admins to create bew users '''

    password = forms.CharField(label='Password', widget=forms.PasswordInput, max_length=254)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('email', 'student', 'instructor', 'admin', 'staff')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)

        if qs.exists():
            raise forms.ValidationError('Email already taken')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match!')
        return password2
    
    def save(self, commit=True):
        # hash the provided password
        user = super(UserAdminRegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user


class UserAdminUpdateForm(forms.ModelForm):
    # update user details from the admin interface
    password = ReadOnlyPasswordHashField(help_text="Raw passwords are not stored, so there is no way to see "
                  "this user's password, but you can change the password "
                  "using <a href=\"password/\">this form</a>.")

    class Meta:
        models = User
        fields = ('email', 'password', 'staff', 'is_active', 'admin', 'student', 'instructor')

    def clean_password(self):
        # render salted password
        return self.initial.get('password')
    

apps/accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, UpdateView
from django.contrib.auth.views import LoginView, AuthenticationForm, PasswordChangeView, PasswordResetView
from .forms import RegistrationForm

# Create your views here.
class LoginView(LoginView):
    template_name = 'login.html'
    form_class = AuthenticationForm


class RegistrationView(CreateView):
    form_class = RegistrationForm
    template_name= 'signup.html'
    success_url = '/'

apps/accounts/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
<div class="row">
    <div class="col col-sm-8 col-md-6 col-lg-6 offset-md-3 offset-lg-3 mt-4">
            <form action="/accounts/login/" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" value="Login" class="btn btn-block btn-success">
                <div class="row text-muted small mt-2">
                    <div class="col-6">
                        <p class="text-left">Forgot password? <a href="/accounts/password_reset">Reset it.</a></p>
                    </div>
                    <div class="col6">New here? <a href="{% url 'authentication:register' %}">Create an account</a></div>
                </div>
            </form>
    </div>
</div>
  
{% endblock %}

{% block footer_content %}{% endblock %}

apps/accounts/templates/password_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
<div class="row">
    <div class="col col-sm-8 col-md-6 col-lg-6 offset-md-3 offset-lg-3 mt-4">
            <form action="/accounts/password_change/" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" value="Reset Password" class="btn btn-block btn-success">
            </form>
    </div>
</div>
  
{% endblock %}

{% block footer_content %}{% endblock %}

apps/accounts/templates/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
<div class="row">
    <div class="col col-sm-8 col-md-6 col-lg-6 offset-md-3 offset-lg-3 mt-4">
            <form action="/accounts/password_reset/" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" value="Reset Password" class="btn btn-block btn-success">
            </form>
    </div>
</div>
  
{% endblock %}

{% block footer_content %}{% endblock %}

apps/accounts/templates/password_reset_done.html
{% extends 'base.html' %}

{% block main_content %}
<div class="col col-md-6 offset-md-3 col-lg-6 offset-lg-3 card-panel">

        <p>
                We've emailed you instructions for setting your password, if an account exists with the email you entered.
                You should receive them shortly.
              </p>
              <p>
                If you don't receive an email, please make sure you've entered the address you registered with,
                and check your spam folder.
              </p>
</div> 
{% endblock %}

{% block footer_content %}{% endblock %}

apps/accounts/templates/password_reset_email.html
1	{% load i18n %}{% autoescape off %}
2	{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}
3	
4	{% trans "Please go to the following page and choose a new password:" %}
5	{% block reset_link %}
6	{{ protocol }}://{{ domain }}{% url 'authentication:password_reset_confirm' uidb64=uid token=token %}
7	{% endblock %}
8	{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}
9	
10	{% trans "Thanks for using our site!" %}
11	
12	{% blocktrans %}The {{ site_name }} team{% endblocktrans %}
13	
14	{% endautoescape %}

apps/accounts/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main_content %}
<div class="row">
    <div class="col col-sm-8 col-md-6 col-lg-6 offset-md-3 offset-lg-3 mt-4">
            <form action="/accounts/register/" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" value="Register" class="btn btn-success btn-block mr-5">
                <p class="ml-5 text-right text-muted small mt-2">Already have an account?<a href="{% url 'authentication:login' %}" class="ml-1">Login</a></p>
            </form>
    </div>
</div>
  
{% endblock %}

{% block footer_content %}{% endblock %}