apps/courses/urls.py
from django.urls import path
from apps.courses import views as c_views 
app_name = 'courses'
urlpatterns = [
   path('', c_views.CoursePackageList.as_view(), name='list'),
   path('new-course/', c_views.NewCourseView.as_view(), name='new-course'),
   path('<course_slug>/add-module/', c_views.CourseModuleAddView.as_view(), name='add-module'),
   path('<course_slug>/', c_views.CourseDetailView.as_view(), name='course-detail'),
   path('<course_slug>/edit-course/', c_views.CourseEditView.as_view(), name='course-edit'),
   path('<course_slug>/delete/', c_views.CoursePackageDeleteView.as_view(), name='course-delete'),
   path('<course_slug>/<module_code>/', c_views.CourseModuleDetailView.as_view(), name='module-detail'),
   path('<course_slug>/<module_code>/edit/', c_views.CourseModuleEditView.as_view(), name='module-edit'),
   path('<course_slug>/<module_code>/delete/', c_views.CourseModuleDeleteView.as_view(), name='module-delete'),
   path('<course_slug>/rate/', c_views.RatingView.as_view(), name='rate-course')

]

elearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.landing.urls', namespace='landing')),
    path('accounts/', include('apps.accounts.urls', namespace='authentication')),
    path('courses/', include('apps.courses.urls', namespace='course'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/courses/models.py
from django.db import models
from apps.accounts.models import User
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import pre_save, post_save, post_delete
from utils.helper_funcs import slug_generator, unique_code_generator, get_average_value
from django.urls import reverse
from django.conf import settings

User = getattr(settings, 'AUTH_USER_MODEL')
RATING_CHOICES = (
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5)
)


class CourseModule(models.Model):
    module_name = models.CharField(max_length=167)
    description = models.TextField()
    module_code = models.CharField(blank=True, max_length=120)
    resource = models.FileField(verbose_name='Learning Resouce', upload_to=f'{module_name.name}/')
    course_package = models.ForeignKey('CoursePackage', on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date_added']
        verbose_name = _('Module')
        verbose_name_plural = _('Modules')
    
    def __str__(self):
        return f"{self.module_name}"

    def get_absolute_url(self):
        return reverse('course:course-detail', kwargs={'course_slug': self.course_package.course_slug})

def module_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.module_code:
        instance.module_code = unique_code_generator(size=8)


pre_save.connect(module_pre_save_receiver, sender=CourseModule)


def module_post_delete_receiver(instance, sender, *args, **kwargs):
    if instance.resource:
        instance.resource.delete(False)

post_delete.connect(module_post_delete_receiver, sender=CourseModule)


class CoursePackage(models.Model):
    course_name = models.CharField(max_length=254)
    course_author = models.ForeignKey(User, on_delete=models.CASCADE)
    course_slug = models.CharField(max_length=124, blank=True)
    course_details = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)

    class Meta:
        ordering = ['-date_added']
        verbose_name = _('Course Packages')
        verbose_name_plural = _('Course Packages')

    def __str__(self):
        return f'{self.course_name}'

    @property
    def average_rating(self):
        return get_average_value(
            model=self.rating_set.model,
            course_id=self.pk,
            rating=self.rating_set.model.rating
        )


def course_package_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.course_slug:
        instance.course_slug = slug_generator(instance)

pre_save.connect(course_package_pre_save_receiver, sender=CoursePackage)


class Rating(models.Model):
    course = models.ForeignKey(CoursePackage, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=RATING_CHOICES)
    rated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.course.course_name}"

    class Meta:
        ordering  = ['-rated_at']

    def get_absolute_url(self):
        return reverse('course:course-detail', kwargs={'course_slug': self.course.course_slug})

apps/courses/forms.py
from django import forms
from .models import CoursePackage, CourseModule
from  .models import Rating


class RatingForm(forms.ModelForm):
    """ Form for enabling a student rate a course """
    class Meta:
        model = Rating
        fields = ('rating',)


class CoursePackageAddForm(forms.ModelForm):
    class Meta:
        model = CoursePackage
        fields = ('course_name', 'course_details', )

class CoursePackageEditForm(forms.ModelForm):
    class Meta:
        model = CoursePackage
        fields = ('course_name', 'course_details', )


class CourseModuleAddForm(forms.ModelForm):
    """ Form for adding modules to a course package """

    class Meta:
        model = CourseModule
        fields = ['module_name', 'description', 'resource' ]

    def clean_resourse(self):
        file = self.cleaned_data.get('resource')
        if file._size > 10485760:
            raise forms.ValidationError('File cannot be bigger than 10mb')
        return file

apps/courses/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    CreateView,
    TemplateView,
    DeleteView,
    UpdateView,
    ListView,
    DetailView,
    FormView
)
from django.urls import reverse_lazy
from .models import CourseModule, CoursePackage, Rating
from .forms import (
    CoursePackageAddForm,
    CourseModuleAddForm,
    CoursePackageEditForm,
    RatingForm
)


class CoursePackageList(ListView):
    queryset = CoursePackage.objects.all()
    context_object_name = 'courses'
    template_name = 'course_list.html'


class CourseDetailView(DetailView, CreateView):
    model = Rating
    form_class = RatingForm
    template_name = 'course_detail.html'
    context_object_name = 'course'


    def get_object(self, *args, **kwargs):
        course_slug = self.kwargs.get("course_slug")
        return get_object_or_404(CoursePackage, course_slug=course_slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        has_rated = Rating.objects.filter(student=self.request.user, course=self.get_object()).exists()
        context['average_rating'] = self.get_object().average_rating
        context['has_rated'] = has_rated
        context['form'] = RatingForm
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.student = self.request.user
        instance.course = self.get_object()
        return super().form_valid(form)

class RatingView(CreateView):
    model = Rating
    form_class = RatingForm

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.student = self.request.user.student
        instance.course = CoursePackage.objects.get(course_slug=self.kwargs.get('course_slug'))
        return super(RatingView, self).form_valid(form)


class CourseModuleDetailView(DetailView):
    template_name = 'module_view.html'
    context_object_name = 'module'

    def get_object(self):
        module_code = self.kwargs.get('module_code')
        return get_object_or_404(CourseModule, module_code=module_code)


class NewCourseView(CreateView):
    model = CoursePackage
    form_class = CoursePackageAddForm
    template_name = 'new_course.html'
    success_url = '/courses/'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.course_author = self.request.user
        return super(NewCourseView, self).form_valid(form)


class CoursePackageDeleteView(DeleteView):
    success_url = reverse_lazy('course:list')
    template_name = 'coursepackage_confirm_delete.html'
    context_object_name = 'course'

    def get_object(self):
        slug = self.kwargs.get('course_slug')
        return get_object_or_404(CoursePackage, course_slug=slug)


class CourseEditView(UpdateView):
    form_class = CoursePackageEditForm
    template_name= 'course_edit.html'
    success_url= '/courses/'

    def get_object(self):
        course_slug = self.kwargs.get('course_slug')
        return get_object_or_404(CoursePackage, course_slug=course_slug)


class CourseModuleAddView(CreateView):
    form_class = CourseModuleAddForm
    template_name = 'module_add.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        course = get_object_or_404(CoursePackage, course_slug=self.kwargs.get('course_slug'))
        instance.course_package = course
        return super(CourseModuleAddView, self).form_valid(form)


class CourseModuleEditView(UpdateView):
    form_class = CourseModuleAddForm
    template_name = 'module_add.html'
    success_url = '/courses/'
    context_object_name = 'module'

    def get_object(self):
        code = self.kwargs.get('module_code')
        return get_object_or_404(CourseModule, module_code=code)

class CourseModuleDeleteView(DeleteView):
    form_class = CourseModuleAddForm
    template_name = 'coursemodule_confirm_delete.html'
    success_url = reverse_lazy('course:list')
    context_object_name = 'module'

    def get_object(self):
        code = self.kwargs.get('module_code')
        return get_object_or_404(CourseModule, module_code=code)

apps/courses/templates/course_detail.html
{% extends 'base.html' %}
{% block title %} Course Detail | {{block.super}} {% endblock %}
{% block header_content %} <p class="display-5 text-center mt-2">{{course.course_name|upper}}</p>{% endblock %}

{% block main_content %}
  <div class="col col-lg-8 offset-lg-2 col-md-10 offset-md-1">
        {% if request.user.is_authenticated and request.user.instructor and request.user == course.course_author %}
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{{request.build_absolute_uri}}add-module/">Add module</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="{{request.build_absolute_uri}}edit-course/">Edit Course</a>
            </li>
        </ul>
        {% endif %}
        <div class="card p-3 mb-2">
            <h4>Course description</h4>
          <p class="text-muted">
              {{course.course_details}}
          </p>
          <p> <span class="mr-3">Rating: {{average_rating}}</span> 
            {% if request.user.student and not has_rated %}
            <form method="POST" action="{{request.build_absolute_uri}}" class=" form-inline">{% include 'rating_form.html' %}</form>
            {% endif %}
          </p>
           
          <ul class="list-group">
                {% for item in course.coursemodule_set.all %}
                <li class="list-group-item"><a href="{{request.build_absolute_uri}}{{item.module_code}}">{{item.module_name}}</a></li>
                {% empty %}
                <li class="list-group-item text-muted">No modules in this course</li>
                {% endfor %}
          </ul>
        </div>
      
  </div>
{% endblock %}
{% block footer_content %}
{% endblock %}

apps/courses/templates/course_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} New Course | {{block.super}} {% endblock %}

{% block main_content %}
<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 mb-2">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="btn btn-block btn-success" value="Save Module"/>
    </form>
</div>
   
{% endblock %}

{% block footer_content %}{% endblock %}

apps/courses/templates/course_list.html
{% extends 'base.html' %}
{% block title %} Course Packages | {{block.super}} {% endblock %}
{% block main_content %}
  
   <div class="col-md-8 offset-md-2 col-lg-8 offset-lg-2">
       <div class="row">
            {% for course in courses %}
         <div class="card col-md-5 col-lg-5 mx-1 my-1">
                <p class="display-5 text-center"><a href="/courses/{{course.course_slug}}">{{course.course_name|truncatechars:20}}</a></p>
                <p class="small">{{course.course_details|truncatechars:45}}</p>
         </div>
         {% endfor %}
       </div>  
   </div>
{% endblock %}
{% block footer_content %}
{% endblock %}

apps/courses/templates/coursemodule_confirm_delete.html
{% extends 'base.html' %}

{% block main_content %}
<div class="card text-center col-md-6 offset-md-3 col-lg-6 offset-lg-3 p-3">
        <form method="post">
                {% csrf_token %}
                <p class="lead">Are you sure you want to delete "{{ module }}"?</p>
                <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
</div>

{% endblock %}

{% block footer_content %}
{% endblock %}

apps/courses/templates/coursepackage_confirm_delete.html
{% extends 'base.html' %}

{% block main_content %}
<div class="card text-center col-md-6 offset-md-3 col-lg-6 offset-lg-3 p-3">
        <form method="post">
                {% csrf_token %}
                <p class="lead">Are you sure you want to delete "{{ course }}"?</p>
                <input type="submit" class="btn btn-danger" value="Confirm">
        </form>
</div>

{% endblock %}

{% block footer_content %}
{% endblock %}

apps/courses/templates/module_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} New Course | {{block.super}} {% endblock %}

{% block main_content %}
<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 mb-2">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="btn btn-block btn-success" value="Save Module"/>
    </form>
</div>
   
{% endblock %}

{% block footer_content %}{% endblock %}

apps/courses/templates/module_view.html
{% extends 'base.html' %}
{% load cloudinary %}
{% cloudinary_includes %}
{% cloudinary_js_config %}
{% load static %}
{% block title %}Viewing | {{block.super}} {% endblock %}

{% block header_content %}
   <h4 class="text-center lead">{{module.module_name|upper}}</h4>
{% endblock %}

{% block main_content %} 
  <div class="col-md-8 offset-md-2 col-lg-8 offset-lg-2">    
          
            <video class="embed-responsive" src="{{module.resource.url}}" controls></video>
            <div class="card p-2 mx-1 my-1">
                {% if request.user.is_authenticated and request.user.instructor and request.user == module.course_package.course_author %}
              <ul class="nav">
                <li class="nav-item mr-2">
                  <a href="{{request.build_absolute_uri}}edit/" class="nav-link">Edit</a>
                </li>
                <li class="nav-item mr-2">
                    <a href="{{request.build_absolute_uri}}delete/" class="nav-link">Delete</a>
                </li>
              </ul>
              {% endif %}
              <p class="text-muted">
                {{module.description}}
              </p>
            </div>
  </div>
{% endblock %}

{% block  footer_content %}{% endblock %}

apps/courses/templates/new_course.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} New Course | {{block.super}} {% endblock %}

{% block main_content %}
<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 mb-2">
    <form method="POST">
        {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="btn btn-block btn-success" value="Save Course"/>
    </form>
</div>
   
{% endblock %}

{% block footer_content %}{% endblock %}

apps/courses/templates/rating_form.html
{% load crispy_forms_tags %}

{% csrf_token %}
{{form|crispy}}
<input type="submit" class="btn btn-success ml-1" value="Submit"/>