apps/accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from .views import (
    LoginView,
    RegistrationView,
    PasswordResetView
)
app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html', success_url='/accounts/password_reset/done'), name='password_reset'),
    path('password_reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(success_url='/accounts/reset/done'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

apps/courses/urls.py
from django.urls import path
from apps.courses import views as c_views 
app_name = 'courses'
urlpatterns = [
   path('', c_views.CoursePackageList.as_view(), name='list'),
   path('new-course/', c_views.NewCourseView.as_view(), name='new-course'),
   path('<course_slug>/add-module/', c_views.CourseModuleAddView.as_view(), name='add-module'),
   path('<course_slug>/', c_views.CourseDetailView.as_view(), name='course-detail'),
   path('<course_slug>/edit-course/', c_views.CourseEditView.as_view(), name='course-edit'),
   path('<course_slug>/delete/', c_views.CoursePackageDeleteView.as_view(), name='course-delete'),
   path('<course_slug>/<module_code>/', c_views.CourseModuleDetailView.as_view(), name='module-detail'),
   path('<course_slug>/<module_code>/edit/', c_views.CourseModuleEditView.as_view(), name='module-edit'),
   path('<course_slug>/<module_code>/delete/', c_views.CourseModuleDeleteView.as_view(), name='module-delete'),
   path('<course_slug>/rate/', c_views.RatingView.as_view(), name='rate-course')

]

apps/landing/urls.py
from django.urls import path
from .views import (LandingView)

app_name = 'landing'
urlpatterns = [
    path('', LandingView.as_view(), name='home')
]

elearning/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.landing.urls', namespace='landing')),
    path('accounts/', include('apps.accounts.urls', namespace='authentication')),
    path('courses/', include('apps.courses.urls', namespace='course'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}E-Learning{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" />
   <style>
       body{
           height:750px;
       }
       .footer{
           position: fixed;
           width:100%;
           bottom: 0px;
           color:#888;
       }
       .banner-section{
           background-image: url("{% static 'images/banner.png' %}");
           background-size:cover;
           height:44vh;
       }
   </style>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container-fluid mb-4"></div>
        {%block header_content %}
            <h4 class="h4 text-center mt-2 text-muted">E-Learning Platform</h4>
        {% endblock %}
        {% block main_content %}Main Content{% endblock %}
    </div>
</body>
        {% block footer_content %}
            <footer class="footer mt-4 py-4 bg-dark">
                <div class="container-fluid">
                    <p class="text-center">&copy; E-Learning {% now 'Y' %}</p>
                </div>
            </footer>
        {% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>

templates/navbar.html
<nav class=" container-fluid navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'landing:home' %}"> <i class="fa fa-globe"></i> &Rightarrow; <i class="fa fa-book"></i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'course:list' %}">Courses</a>
            </li>
            <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search courses">
                    <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
                  </form>
          </ul>

          <ul class="navbar-nav ml-auto">
              {% if request.user.instructor %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'course:new-course' %}"> <i class="fa fa-plus"></i> Course</a>
              </li>
                
              {% endif %}
                <li class="nav-item dropdown mr-4">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="far fa-user"></i>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if request.user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'authentication:logout' %}">Logout</a>
                    {% else %}
                    <a class="dropdown-item" href="{% url 'authentication:login' %}">Login</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'authentication:register' %}">Register</a>
                    {% endif %}
                  </div>
                </li>
          </ul>
          
        </div>
      </nav>